name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  YAML_MANIFEST_URL: "http://foo/bar/manifest.yaml"
  OBJECT_TYPE: "OBJ_TPE"
  APPLICATION_NAME: "foo"
  LOCAL_PREFIX: "/tmp"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
